var eastData = {
	"Antlantic": {
		"headerTitle": "Atlantic",
		"footerTitle": "Atlantic",
		"rowData": [
			{name: "Boston Celtics", 
			record: "15-29", 
			rank: "26th", 
			ppg: "95.0", 
			apg:"19.7", 
			rpg:"42.8", 
			bpg:"4.7", 
			scorer:"Eastern/Celtics/jeff-green.jpg", 
			assist:"Eastern/Celtics/jordan-crawford.jpg", 
			fg:"Eastern/Celtics/",
			logo: "Eastern/Celtics/boston.gif", 
			name1: "J. Green", 
			name2:"J. Crawford", 
			name3:"G. Wallace", 
			stat1:"15.6 pts",
			stat2:"5.74 ast",
			stat3:"52.6 fg%",
			id:"1"  },
			
			{name: "Brooklyn Nets", 
			record: "18-22", 
			rank: "16th", 
			ppg: "97.3", 
			apg:"20.8", 
			rpg:"40.0", 
			bpg:"4.1", 
			scorer:"Eastern/Nets/joe-johnson.jpg", 
			assist:"Eastern/Nets/shaun-livingston.jpg", 
			fg:"Eastern/Nets/mason-plumlee.jpg",
			logo:"Eastern/Nets/brooklyn.jpg", 
			name1:"J. Johnson", 
			name2:"S.Livingston", 
			name3:"M. Plumlee",
			stat1:"16.2 pts",
			stat2:"3.18 ast",
			stat3:"62.7 fg%", 
			id:"2",  },
			
			{name: "New York Knicks", 
			record: "15-27", 
			rank: "20th", 
			ppg: "94.9", 
			apg:"20.1", 
			rpg:"40.3", 
			bpg:"4.4", 
			scorer:"Eastern/Knicks/carmelo-anthony.jpg", 
			assist:"Eastern/Knicks/carmelo-anthony.jpg", 
			fg:"Eastern/Knicks/jeremy-tyler.jpg",
			logo:"Eastern/Knicks/new-york.jpg", 
			name1:"C. Anthony", 
			name2:"C. Anthony", 
			name3:"J. Tyler", 
			stat1:"26.1 pts",
			stat2:"3.0 ast",
			stat3:"80.0 fg%",
			id:"3",  },
			
			{name: "Philadelphia 76ers", 
			record: "14-28", 
			rank: "28th", 
			ppg: "101.2", 
			apg:"22.4", 
			rpg:"44.9", 
			bpg:"4.3", 
			scorer:"Eastern/76ers/evan-turner.jpg", 
			assist:"Eastern/76ers/evan-turner.jpg", 
			fg:"Eastern/76ers/thaddeus-young.jpg",
			logo:"Eastern/76ers/philadelphia.jpg", 
			name1:"E. Turner", 
			name2:"E. Turner", 
			name3:"T. Young",
			stat1:"18.9 pts",
			stat2:"3.86 ast",
			stat3:"49.9 fg%", 
			id:"4",  },
			
			{name: "Toronto Raptors", 
			record: "21-20", 
			rank: "11th", 
			ppg: "98.8", 
			apg:"20.2", 
			rpg:"43.3", 
			bpg:"4.6", 
			scorer:"Eastern/Raptors/demar-derozan.jpg", 
			assist:"Eastern/Raptors/kyle-lowry.jpg", 
			fg:"Eastern/Raptors/aaron-gray.jpg",
			logo:"Eastern/Raptors/toronto.jpg", 
			name1:"D. Derozan", 
			name2:"K. Lowry", 
			name3:"A. Gray",
			stat1:"21.3 pts",
			stat2:"7.43 ast",
			stat3:"66.7 fg%", 
			id:"5",  },			
		]
	},
	"Central": {
		"headerTitle": "Central",
		"footerTitle": "Central",
		"rowData": [
			{name: "Chicago Bulls", 
			record: "21-20", 
			rank: "13th", 
			ppg: "92.8", 
			apg:"22.2", 
			rpg:"45.3", 
			bpg:"5.2", 
			scorer:"Eastern/Bulls/carlos-boozer.jpg", 
			assist:"Eastern/Bulls/joakim-noah.jpg", 
			fg:"Eastern/Bulls/taj-gibson.jpg",
			logo:"Eastern/Bulls/chicago.jpg", 
			name1:"C. Boozer", 
			name2:"J. Noah", 
			name3:"T. Gibson",
			stat1:"15.0 pts",
			stat2:"3.81 ast",
			stat3:"48.4 fg%", 
			id:"6",  },
			
			{name: "Cleveland Cavaliers", 
			record: "15-27", 
			rank: "21st", 
			ppg: "96.7", 
			apg:"19.4", 
			rpg:"44.5", 
			bpg:"4.3", 
			scorer:"Eastern/Cavaliers/kyrie-irving.jpg", 
			assist:"Eastern/Cavaliers/kyrie-irving.jpg", 
			fg:"Eastern/Cavaliers/tyler-zeller.jpg",
			logo:"Eastern/Cavaliers/cleveland.jpg", 
			name1:"K. Irving", 
			name2:"K. Irving", 
			name3:"T. Zeller",
			stat1:"21.5 pts",
			stat2:"6.03 ast",
			stat3:"54.0 fg%", 
			id:"7",  },
			
			{name: "Detroit Pistons", 
			record: "17-25", 
			rank: "19th", 
			ppg: "99.4", 
			apg:"20.4", 
			rpg:"44.7", 
			bpg:"5.3", 
			scorer:"Eastern/Pistons/brandon-jennings.jpg", 
			assist:"Eastern/Pistons/brandon-jennings.jpg", 
			fg:"Eastern/Pistons/tony-mitchell.jpg",
			logo:"Eastern/Pistons/detroit.jpg", 
			name1:"B. Jennings", 
			name2:"B. Jennings", 
			name3:"T. Mitchell",
			stat1:"16.5 pts",
			stat2:"8.41 ast",
			stat3:"60.0 fg%", 
			id:"8",  },
			
			{name: "Indiana Pacers", 
			record: "33-8", 
			rank: "1st",
			ppg: "98.2", 
			apg:"20.8", 
			rpg:"44.9", 
			bpg:"5.9", 
			scorer:"Eastern/Pacers/paul-george.jpg", 
			assist:"Eastern/Pacers/lance-stephenson.jpg", 
			fg:"Eastern/Pacers/rasual-butler.jpg",
			logo:"Eastern/Pacers/indiana.jpg", 
			name1:"P. George", 
			name2:"L. Stephenson", 
			name3:"R. Butler",
			stat1:"22.9 pts",
			stat2:"5.14 ast",
			stat3:"52.9 fg%", 
			id:"9",  },
			
			{name: "Milwaukee Bucks", 
			record: "8-33", 
			rank: "30th", 
			ppg: "91.4", 
			apg:"20.6", 
			rpg:"41.3", 
			bpg:"5.6", 
			scorer:"Eastern/Bucks/oj-mayo.jpg", 
			assist:"Eastern/Bucks/oj-mayo.jpg", 
			fg:"Eastern/Bucks/miroslav-raduljica.jpg",
			logo:"Eastern/Bucks/milwaukee.jpg", 
			name1:"O. Mayo", 
			name2:"O. Mayo", 
			name3:"M. Raduljica",
			stat1:"13.0 pts",
			stat2:"2.38 ast",
			stat3:"59.2 fg%", 
			id:"10", },
		]
	},
	"Southeast": {
		"headerTitle": "Southeast",
		"footerTitle": "Southeast",
		"rowData": [
			{name: "Atlanta Hawks", 
			record: "22-19", 
			rank: "15th", 
			ppg: "102.2", 
			apg:"25.6", 
			rpg:"40.9", 
			bpg:"4.4", 
			scorer:"Eastern/Hawks/paul-millsap.jpg", 
			assist:"Eastern/Hawks/jeff-teague.jpg", 
			fg:"Eastern/Hawks/al-horford.jpg"
			, logo:"Eastern/Hawks/atlanta.jpg", 
			name1:"P. Millsap", 
			name2:"J. Teague", 
			name3:"A. Horford",
			stat1:"17.3 pts",
			stat2:"7.62 ast",
			stat3:"66.7 fg%", 
			id:"11",  },
			
			{name: "Charlotte Bobcats", 
			record: "19-25", 
			rank: "24th", 
			ppg: "94.0", 
			apg:"20.1", 
			rpg:"41.8", 
			bpg:"5.0", 
			scorer:"Eastern/Bobcats/kemba-walker.jpg", 
			assist:"Eastern/Babcats/kemba-walker.jpg", 
			fg:"Eastern/Bobcats/bismack-biyombo.jpg"
			, logo:"Eastern/Bobcats/charlotte.jpg", 
			name1:"K. Walker", 
			name2:"K. Walker", 
			name3:"B. Biyombo",
			stat1:"19.0 pts",
			stat2:"4.85 ast",
			stat3:"61.3 fg%", 
			id:"12",  },
			
			{name: "Miami Heat", 
			record: "31-12",
			rank: "6th", 
			ppg: "104.0", 
			apg:"23.5", 
			rpg:"36.5", 
			bpg:"4.5", 
			scorer:"Eastern/Heat/lebron-james.jpg", 
			assist:"Eastern/Heat/lebron-james.jpg", 
			fg:"Eastern/Heat/greg-oden.jpg"
			, logo:"Eastern/Heat/miami.jpg", 
			name1:"L. James", 
			name2:"L. James", 
			name3:"G. Oden",
			stat1:"25.9 pts",
			stat2:"6.49 ast",
			stat3:"66.7 fg%", 
			id:"13",  },
			
			{name: "Orlando Magic", 
			record: "11-32", 
			rank: "29th", 
			ppg: "95.9", 
			apg:"20.5", 
			rpg:"42.6", 
			bpg:"4.3", 
			scorer:"Eastern/Magic/arron-afflalo.jpg", 
			assist:"Eastern/Magic/jameer-nelson.jpg", 
			fg:"Eastern/Magic/nikola-vucevic.jpg"
			, logo:"Eastern/Magic/orlando.jpg", 
			name1:"A. Afflalo", 
			name2:"J. Nelson", 
			name3:"N. Vucevic",
			stat1:"20.8 pts",
			stat2:"6.47 ast",
			stat3:"51.0 fg%", 
			id:"14",  },
			
			{name: "Washington Wizards", 
			record: "20-21", 
			rank: "14th", 
			ppg: "98.5", 
			apg:"23.1", 
			rpg:"42.5", 
			bpg:"4.8", 
			scorer:"Eastern/Wizards/john-wall.jpg", 
			assist:"Eastern/Wizards/john-wall.jpg", 
			fg:"Eastern/Wizards/trevor-booker.jpg"
			, logo:"Eastern/Wizards/wizards.jpg", 
			name1:"J. Wall", 
			name2:"J. Wall", 
			name3:"T. Booker",
			stat1:"19.7 pts",
			stat2:"8.57 ast",
			stat3:"55.0 fg%", 
			id:"15",  },
		]
	},
};
var westData = {
	"Northwest": {
		"headerTitle": "Northwest",
		"footerTitle": "Northwest",
		"rowData": [
			{name: "Denver Nuggets", 
			record: "20-21", 
			rank: "17th", 
			ppg: "103.3", 
			apg:"22.1", 
			rpg:"45.9", 
			bpg:"5.8", 
			scorer:"Western/Nuggets/ty-lawson.jpg", 
			assist:"Western/Nuggets/ty-lawson.jpg", 
			fg:"Western/Nuggets/timofey-mozgov.jpg"
			, logo:"Western/Nuggets/denver.jpg", 
			name1:"T. Lawson", 
			name2:"T. Lawson", 
			name3:"T. Mozgov",
			stat1:"17.8 pts",
			stat2:"8.58 ast",
			stat3:"56.2 fg%", 
			id:"16",  },
			
			{name: "Minnesota Timberwolves", 
			record: "20-21", 
			rank: "18th", 
			ppg: "106.5", 
			apg:"23.6", 
			rpg:"46.1", 
			bpg:"3.2", 
			scorer:"Western/Timberwolves/kevin-love.jpg", 
			assist:"Western/Timberwolves/ricky-rubio.jpg", 
			fg:"Western/Timberwolves/nikola-pekovic.jpg"
			, logo:"Western/Timberwolves/minnesota.jpg", 
			name1:"K. Love", 
			name2:"R. Rubio", 
			name3:"C. Budinger",
			stat1:"26.1 pts",
			stat2:"8.29 ast",
			stat3:"66.7 fg%", 
			id:"17", 
			leaderID:"6"  },
			
			{name: "Oklahoma City Thunder", 
			record: "33-10", 
			rank: "3rd", 
			ppg: "105.3", 
			apg:"21.4", 
			rpg:"46.7", 
			bpg:"6.2", 
			scorer:"Western/Thunder/kevin-durant.jpg", 
			assist:"Western/Thunder/kevin-durant.jpg", 
			fg:"Western/Thunder/andre-roberson.jpg"
			, logo:"Western/Thunder/oklahoma.jpg", 
			name1:"K. Durant", 
			name2:"K. Durant", 
			name3:"A. Roberson",
			stat1:"29.5 pts",
			stat2:"4.89 ast",
			stat3:"57.1 fg%", 
			id:"18", 
			leaderID:"3"  },
			
			{name: "Portland Trail Blazers", 
			record: "32-11", 
			rank: "2nd", 
			ppg: "109.3", 
			apg:"24.5", 
			rpg:"46.6", 
			bpg:"4.7", 
			scorer:"Western/Trail Blazers/lamarcus-aldridge.jpg", 
			assist:"Western/Trail Blazers/nicolas-batum.jpg", 
			fg:"Western/Trail Blazers/robin-lopez.jpg"
			, logo:"Western/Trail Blazers/portland.jpg", 
			name1:"L. Aldridge", 
			name2:"N. Batum", 
			name3:"R. Lopez",
			stat1:"23.7 pts",
			stat2:"5.67 ast",
			stat3:"55.0 fg%", 
			id:"19",  },
			
			{name: "Utah Jazz", 
			record: "14-29", 
			rank: "23rd", 
			ppg: "94.5", 
			apg:"20.3", 
			rpg:"41.3", 
			bpg:"4.9", 
			scorer:"Western/Jazz/gordon-hayward.jpg", 
			assist:"Western/Jazz/gordon-hayward.jpg", 
			fg:"Western/Jazz/andris-biedrins.jpg"
			, logo:"Western/Jazz/Utah.jpg", 
			name1:"G. Hayward", 
			name2:"G. Hayward", 
			name3:"A. Biedrins",
			stat1:"17.1 pts",
			stat2:"4.89 ast",
			stat3:"100 fg%", 
			id:"20",  },			
		]
	},
	"Pacific": {
		"headerTitle": "Pacific",
		"footerTitle": "Pacific",
		"rowData": [
			{name: "Golden State Warriors", 
			record: "26-17", 
			rank: "5th", 
			ppg: "103.6", 
			apg:"23.0", 
			rpg:"45.9", 
			bpg:"5.0", 
			scorer:"Western/Warriors/stephen-curry.jpg", 
			assist:"Western/Warriors/stephen-curry.jpg", 
			fg:"Western/Warriors/"
			, logo:"Western/Warriors/golden.jpg", 
			name1:"S. Curry", 
			name2:"S. Curry", 
			name3:"H. Armstrong",
			stat1:"23.1 pts",
			stat2:"9.4 ast",
			stat3:"66.7 fg%", 
			id:"21",  },
			
			{name: "Los Angeles Clippers", 
			record: "29-15", 
			rank: "7th", 
			ppg: "105.4", 
			apg:"23.8", 
			rpg:"43.1", 
			bpg:"4.8", 
			scorer:"Western/Clippers/blake-griffin.jpg", 
			assist:"Western/Clippers/chris-paul.jpg", 
			fg:"Western/Clippers/ryan-hollins.jpg"
			, logo:"Western/Clippers/laclippers.jpg", 
			name1:"B. Griffin", 
			name2:"C. Paul", 
			name3:"R. Hollins",
			stat1:"22.3 pts",
			stat2:"11.2 ast",
			stat3:"68.3 fg%", 
			id:"22", 
			leaderID:"4"},
			
			{name: "Los Angeles Lakers", 
			record: "16-27", 
			rank: "25th", 
			ppg: "100.6", 
			apg:"22.5", 
			rpg:"42.7", 
			bpg:"5.7", 
			scorer:"Western/Lakers/nick-young.jpg", 
			assist:"Western/Lakers/pau-gasol.jpg", 
			fg:"Western/Lakers/jordan-hill.jpg"
			, logo:"Western/Lakers/lakers.jpg", 
			name1:"N. Young", 
			name2:"P. Gasol", 
			name3:"J. Hill", 
			stat1:"16.4 pts",
			stat2:"3.33 ast",
			stat3:"56.1 fg%",
			id:"23",  },
			
			{name: "Phoenix Suns", 
			record: "24-17", 
			rank: "12th", 
			ppg: "104.4", 
			apg:"19.0", 
			rpg:"43.6", 
			bpg:"5.0", 
			scorer:"Western/Suns/goran-dragic.jpg", 
			assist:"Western/Suns/goran-dragic.jpg", 
			fg:"Western/Suns/viacheslav-kravtsov.jpg"
			, logo:"Western/Suns/phoenix.jpg", 
			name1:"G. Dragic", 
			name2:"G. Dragic", 
			name3:"V. Kravtsov", 
			stat1:"19.1 pts",
			stat2:"5.9 ast",
			stat3:"60.0 fg%",
			id:"24",  },
			
			{name: "Sacramento Kings", 
			record: "15-26", 
			rank: "22nd", 
			ppg: "101.7", 
			apg:"20.1", 
			rpg:"43.5", 
			bpg:"4.1", 
			scorer:"Western/Kings/demarcus-cousins.jpg", 
			assist:"Western/Kings/isaiah-thomas.jpg", 
			fg:"Western/Kings/"
			, logo:"Western/Kings/sacramento.jpg", 
			name1:"D. Cousins", 
			name2:"I. Thomas", 
			name3:"Q. Acy", 
			stat1:"23.5 pts",
			stat2:"6.24 ast",
			stat3:"54.5 fg%",
			id:"25",  },
		]
	},
	"Southwest": {
		"headerTitle": "Southwest",
		"footerTitle": "Southwest",
		"rowData": [
			{name: "Dallas Mavericks", 
			record: "25-19", 
			rank: "10th", 
			ppg: "103.5", 
			apg:"23.5", 
			rpg:"39.8", 
			bpg:"4.2", 
			scorer:"Western/Mavericks/dirk-nowitzki.jpg", 
			assist:"Western/Mavericks/monta-ellis.jpg", 
			fg:"Western/Mavericks/brandan-wright.jpg"
			, logo:"Western/Mavericks/dallas.jpg", 
			name1:"D. Nowitzki", 
			name2:"M. Ellis", 
			name3:"B. Wright", 
			stat1:"20.7 pts",
			stat2:"5.86 ast",
			stat3:"71.8 fg%",
			id:"26",  },
			
			{name: "Houston Rockets", 
			record: "29-15", 
			rank: "8th", 
			ppg: "105.9", 
			apg:"20.4", 
			rpg:"45.4", 
			bpg:"6.0", 
			scorer:"Western/Rockets/james-harden.jpg", 
			assist:"Western/Rockets/dwight-howard.jpg", 
			fg:"Western/Rockets/greg-smith.jpg"
			, logo:"Western/Rockets/houston.jpg", 
			name1:"J. Harden", 
			name2:"D. Howard", 
			name3:"G. Smith",
			stat1:"24.9 pts",
			stat2:"1.83 ast",
			stat3:"62.5 fg%", 
			id:"27",  },
			
			{name: "Memphis Grizzlies", 
			record: "20-20", 
			rank: "9th", 
			ppg: "95.8", 
			apg:"21.5", 
			rpg:"43.1", 
			bpg:"4.6", 
			scorer:"Western/Grizzlies/mike-conley.jpg", 
			assist:"Western/Grizzlies/mike-conley.jpg", 
			fg:"Western/Grizzlies/ed-davis.jpg"
			, logo:"Western/Grizzlies/memphis.jpg", 
			name1:"M. Conley", 
			name2:"M. Conley", 
			name3:"E. Davis",
			stat1:"17.6 pts",
			stat2:"6.28 ast",
			stat3:"56.3 fg%",
			id:"28",  },
			
			{name: "New Orleans Pelicans", 
			record: "16-25", 
			rank: "27th", 
			ppg: "100.7", 
			apg:"21.9", 
			rpg:"42.9", 
			bpg:"6.2", 
			scorer:"Western/Pelicans/eric-gordon.jpg", 
			assist:"Western/Pelicans/jrue-holiday.jpg", 
			fg:"Western/Pelicans/jeff-withey.jpg"
			, logo:"Western/Pelicans/new.png", 
			name1:"E. Gordon", 
			name2:"J. Holiday", 
			name3:"J. Whithey",
			stat1:"15.6 pts",
			stat2:"7.88 ast",
			stat3:"70.0 fg%", 
			id:"29", 
			leaderID:"2"  },
			
			{name: "San Antonio Spurs", 
			record: "32-10", 
			rank: "4th", 
			ppg: "104.8", 
			apg:"25.2", 
			rpg:"42.9", 
			bpg:"4.7", 
			scorer:"Western/Spurs/tony-parker.jpg", 
			assist:"Western/Spurs/tony-parker.jpg", 
			fg:"Western/Spurs/boris-diaw.jpg"
			, logo:"Western/Spurs/San.jpg", 
			name1:"T. Parker", 
			name2:"T. Parker", 
			name3:"B. Diaw", 
			stat1:"17.7 pts",
			stat2:"6.18 ast",
			stat3:"55.2 fg%",
			id:"30", 
			leaderID:"1"  },
		]
	},
};
var lead = {
	"Leaders": [
			{name: "Marco Belinelli", team: "SAS", statname: "3-Point Field Goal %", stat: "49.3%"},
			{name: "Anthony Davis", team: "NOP", statname: "Blocks Per Game", stat: "3.0"},
			{name: "Kevin Durant", team: "OKC", statname: "Points Per Game", stat: "31.0"},
			{name: "DeAndre Jordan", team: "LAC", statname: "Rebounds Per Game", stat: "13.9"},
			{name: "DeAndre Jordan", team: "LAC", statname: "Field Goal %", stat: "64.1%"},
			{name: "Kevin Martin", team: "MIN", statname: "Free Throw %", stat: "91.3%"},
			{name: "Chris Paul", team: "LAC", statname: "Assists Per Game", stat: "11.2"},
			{name: "Ricky Rubio", team: "MIN", statname: "Steals Per Game", stat: "2.66"},		
		]
};
var gallery = {
	"pics": [
			{pic: "nbagallery/atlhawks.jpg", explanation: "Atlanta Hawks Shooting guard Kyle Korver."},
			{pic: "nbagallery/blake.jpg", explanation: "Los Angelas Clippers power forward Blake Griffin."},
			{pic: "nbagallery/chicagobulls.jpg", explanation: "Chicago Bulls point guard Derrick Rose."},
			{pic: "nbagallery/clevelandcavs.jpg", explanation: "Cleveland Cavaliers point guard Kyrie Irving"},
			{pic: "nbagallery/curry.jpg", explanation: "Golden State Warriors point guard Stephen Curry."},
			{pic: "nbagallery/det.jpg", explanation: "Detroit Pistons center Ander Drummond."},
			{pic: "nbagallery/gold.jpg", explanation: "Golden State Warriors small forward Andre Iguodala."},
			{pic: "nbagallery/howard.jpg", explanation: "Houston Rockets center Dwight Howard."},
			{pic: "nbagallery/james.jpg", explanation: "Houston Rockets guard James Harden."},	
			{pic: "nbagallery/jazz.jpg", explanation: "Utah Jazz shooting guard Gordon Hayward."},	
			{pic: "nbagallery/knicks.jpg", explanation: "New York Knicks pwer forward Carmelo Anthony"},
			{pic: "nbagallery/lac.jpg", explanation: "Los Angelos Clippers point guard Cgris Paul."},
			{pic: "nbagallery/lebron.jpg", explanation: "Miami Heat forward LeBron James."},
			{pic: "nbagallery/minn.jpg", explanation: "Minnesota Timberwolves power forward Kevin Love."},
			{pic: "nbagallery/nets.jpg", explanation: "Brooklyn Nets pount guard Deron Williams."},
			{pic: "nbagallery/No.jpg", explanation: "New Orleans Pelicans power forward Anthony Davis."},
			{pic: "nbagallery/nugg.jpg", explanation: "Denver Nuggets power forward Kenneth Faried."},
			{pic: "nbagallery/okc.jpg", explanation: "Oklahoma City Thunder point guard Russel Westbrook."},
			{pic: "nbagallery/port.jpg", explanation: "Portland Trail Blazers power forward LaMarcus Aldridge."},	
			{pic: "nbagallery/spur.jpg", explanation: "San Antonio Spurs small forward Kawhi Leonard."},	
			{pic: "nbagallery/state.jpg", explanation: "Golden State Warriors shooting guard Klay Thompson."},
			{pic: "nbagallery/tyson.jpg", explanation: "New York Knicks center Tyson Chandler."},
			{pic: "nbagallery/whowill.jpg", explanation: "Who will represent Team USA? USA Basketball announced a pool of 28 players who will form 12-man rosters for the 2014 World Cup and 2016 Olympics."},
			{pic: "nbagallery/wiz.jpg", explanation: "Washington Wizards shooting guard Bradley Beal."},	
		]
		
};
